# This file is used to configure your dbt project.
name: "duckdb"
version: "1.0.0"
config-version: 2

profile: "database_duckdb"

# Project file directories
model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]
test-paths: ["tests"]

# Output directories
target-path: "target"
clean-targets: ["target", "dbt_packages"]

# Default configuration for models
models:
  duckdb:
    staging:
      +schema: staging
      +materialized: incremental
      +incremental_strategy: delete+insert